name: CI

on:
  push:
    branches: ['*']
  pull_request:
    branches: [main]

env:
  HUSKY: 0

jobs:
  lint:
    name: Static code analysis
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Biome
        uses: biomejs/setup-biome@v2

      - name: Run linting
        run: biome lint

  format:
    name: Formatting
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Biome
        uses: biomejs/setup-biome@v2

      - name: Run formatting
        run: biome format

  typescript:
    name: Type checking
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Cache Yarn cache
        uses: actions/cache@v5
        env:
          cache-name: yarn-cache
        with:
          path: ~/.yarn/berry/cache
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22.18.0'

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn --immutable

      - name: Run type checking
        run: yarn tsc

  unit:
    name: Unit tests
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Cache Yarn cache
        uses: actions/cache@v5
        env:
          cache-name: yarn-cache
        with:
          path: ~/.yarn/berry/cache
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22.18.0'

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn --immutable

      - name: Run unit tests
        run: yarn unit
